# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
ENV['SWIFT_VERSION'] = '4.2'
target 'RNFluidicSlider' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RNFluidicSlider
  pod 'fluid-slider', :git => 'https://github.com/Ramotion/fluid-slider'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name.include?('fluid-slider')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.2'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
      end
    end
  end
end
